### ISSUE TITLE
Dode links naar Docker Desktop

### ISSUE THREAD

**Issue by ItsSiem** [Windesheim-HBO-ICT/Leerlijn-SE#18]
Links naar docker desktop (installatie handleiding?) werken niet.
https://github.com/Windesheim-HBO-ICT/Leerlijn-SE/blob/c57d6d1c246f7623feb2868be337137bef92aea1/3.%20Procedurele%20informatie/Security/Workshops/7.%20Workshop%20Juiceshop%20I/1.%20Introductie.md?plain=1#L5
https://github.com/Windesheim-HBO-ICT/Leerlijn-SE/blob/c57d6d1c246f7623feb2868be337137bef92aea1/3.%20Procedurele%20informatie/Security/Workshops/8.%20Workshop%20Juiceshop%20II/1.%20Introductie.md?plain=1#L5

**Comment by TeunvdKleij** [comment]
Klopt, dit waren oude references, is opgelost in een pull request
